Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.boot_timeout = 600
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
end
