- hosts: api
  become: yes
  become_user: root
  vars_files:
    - "group_vars/defaults.yml"
    - "group_vars/{{ inventory }}.yml"
  vars:
    busapi_bin_path: "/usr/local/bin/busapi"
    busapi_conf_path: "/etc/init/busapi.conf"
    busapi_user: "bus"

  tasks:
    - name: Install needed packages
      apt: update_cache=yes pkg="{{ item }}" state=installed
      with_items:
        - monit
        - redis-server

    - name: Create bus user
      user: name="{{ busapi_user }}"

    - name: Create bus web directory
      file: path="{{ web_dir }}" owner=bus mode=755 state=directory

    - name: Copy static web assets
      copy: src=../web/ dest="{{ web_dir }}"

    - name: Install busapi binary
      copy: src=bin/busapi dest="{{ busapi_bin_path }}" mode=755

    - name: setcap to bind lower ports as non-root
      command: setcap cap_net_bind_service=+ep "{{ busapi_bin_path }}"

    - name: Install busapi upstart config
      template: src=templates/busapi_upstart.conf.j2 dest="{{ busapi_conf_path }}" owner=root group=root mode=644

    - name: Reload upstart config
      command: initctl reload-configuration

    - name: Install api monit config
      template: src=templates/api_monit.conf.j2 dest=/etc/monit/conf.d/api_monit.conf owner=root group=root mode=644

    - name: Reload monit config
      service: name=monit state=reloaded

    - name: Restart buspi
      service: name=busapi state=restarted
