# db.yml is a playbook to run during a typical deploy. It will run any 
# new migrations, etc.  

- include: db_common.yml

- hosts: db
  become: yes
  become_user: root
  vars:
    - flyway_version: 4.0.3
    - flyway_url: "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/{{ flyway_version }}/flyway-commandline-{{ flyway_version }}-linux-x64.tar.gz"
    - flyway_file: "flyway-commandline-{{ flyway_version }}-linux-x64.tar.gz"
    - flyway_dir: "/usr/local/flyway-{{ flyway_version }}"

  vars_files:
    - "group_vars/defaults.yml"
    - "group_vars/{{ inventory }}.yml"


  tasks:

    - name: Get Flyway
      get_url: url="{{ flyway_url }}" dest="/tmp/{{ flyway_file }}"

    - name: Unarchive Flyway
      unarchive: src="/tmp/{{ flyway_file }}" dest="/usr/local" copy=no 

    - name: Allow all to execute Flyway
      file: mode=0755 path="{{ flyway_dir }}/flyway"

    - name: Copy migrations
      copy: src=../migrations dest=/usr/local

    - name: Execute migrations
      command: "{{ flyway_dir }}/flyway -user=postgres -password= -url='jdbc:postgresql://localhost/postgres' -locations=filesystem:/usr/local/migrations migrate"


